# Generated by Django 5.0.2 on 2024-02-21 10:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "choice",
                    models.IntegerField(
                        choices=[(1, "出席"), (2, "欠席")], default=1, verbose_name="出欠予定"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="最新更新日時"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Kid_Information",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=6, unique=True, verbose_name="登録番号"),
                ),
                ("first_name", models.CharField(max_length=20, verbose_name="名")),
                ("family_name", models.CharField(max_length=20, verbose_name="姓")),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="メールアドレス"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="作成日時"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "attendance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="attendance.attendance",
                        verbose_name="本日の出欠予定",
                    ),
                ),
            ],
        ),
    ]
