# Generated by Django 5.0.2 on 2024-03-02 02:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("full_name", models.CharField(max_length=100)),
                (
                    "gender",
                    models.CharField(choices=[("M", "男"), ("F", "女")], max_length=1),
                ),
            ],
        ),
    ]
