# Generated by Django 5.0.2 on 2024-06-28 08:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="dummy_field",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
