# Generated by Django 5.0.2 on 2024-05-22 08:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance_info",
            name="end_time",
            field=models.TimeField(blank=True, null=True, verbose_name="終了時間"),
        ),
        migrations.AlterField(
            model_name="attendance_info",
            name="start_time",
            field=models.TimeField(blank=True, null=True, verbose_name="開始時間"),
        ),
    ]
