# Generated by Django 5.0.2 on 2024-03-04 12:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0002_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="calendar_date",
            field=models.DateField(null=True),
        ),
    ]
