# Generated by Django 5.0.2 on 2024-06-28 08:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0002_user_dummy_field"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="dummy_field",
        ),
    ]
