# Generated by Django 5.0.2 on 2024-06-11 10:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0003_attendance_info_inputter_attendance_info_updater"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weekday",
                    models.CharField(
                        choices=[
                            ("mon", "月曜日"),
                            ("tue", "火曜日"),
                            ("wed", "水曜日"),
                            ("thu", "木曜日"),
                            ("fri", "金曜日"),
                            ("sat", "土曜日"),
                            ("sun", "日曜日"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("group_morning", "集団 (午前)"),
                            ("group_afternoon", "集団 (午後)"),
                            ("individual_afternoon", "個別 (午後)"),
                            ("after_school", "放課後デイサービス (個別午後)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
            ],
        ),
    ]
