# Generated by Django 5.0.2 on 2024-06-30 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0003_remove_user_dummy_field"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="services",
        ),
        migrations.AddField(
            model_name="user",
            name="service_type",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to="attendance.servicetime",
            ),
        ),
        migrations.AlterField(
            model_name="servicetime",
            name="weekday",
            field=models.CharField(max_length=3),
        ),
    ]
