# Generated by Django 5.0.2 on 2024-06-30 07:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0004_remove_user_services_user_service_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="service_type",
        ),
        migrations.AddField(
            model_name="user",
            name="services",
            field=models.ManyToManyField(
                related_name="users",
                to="attendance.servicetime",
                verbose_name="利用するサービス",
            ),
        ),
    ]
