# Generated by Django 5.0.2 on 2024-06-30 07:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0005_remove_user_service_type_user_services"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="services",
        ),
        migrations.AddField(
            model_name="user",
            name="service_type",
            field=models.CharField(
                choices=[
                    ("group_morning", "集団 (午前)"),
                    ("group_afternoon", "集団 (午後)"),
                    ("individual_morning", "個別（午前）"),
                    ("individual_afternoon", "個別 (午後)"),
                    ("after_school", "放課後デイサービス (個別午後)"),
                ],
                default="group_morning",
                max_length=50,
                verbose_name="サービスの種類",
            ),
        ),
        migrations.AlterField(
            model_name="servicetime",
            name="weekday",
            field=models.CharField(
                choices=[
                    ("mon", "月曜日"),
                    ("tue", "火曜日"),
                    ("wed", "水曜日"),
                    ("thu", "木曜日"),
                    ("fri", "金曜日"),
                    ("sat", "土曜日"),
                    ("sun", "日曜日"),
                ],
                max_length=3,
            ),
        ),
    ]
