# Generated by Django 5.0.2 on 2024-04-25 02:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0006_alter_absenceaccrual_attendance"),
    ]

    operations = [
        migrations.RenameField(
            model_name="attendance_info",
            old_name="date",
            new_name="calendar_date",
        ),
        migrations.AlterField(
            model_name="user",
            name="recipient_number",
            field=models.CharField(
                blank=True, max_length=20, null=True, unique=True, verbose_name="受給者番号"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="attendance_info",
            unique_together={("user", "calendar_date")},
        ),
    ]
